user_authentication/user_authentication/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_authentication_app.urls')),
]

user_authentication/user_authentication_app/urls.py
from django.conf.urls import url
from django.urls import path
from user_authentication_app import views

app_name = "user_authentication_app"

urlpatterns = [
     path('', views.index, name='index'),
     path('register/', views.register, name='register'),
     path('log_in/', views.log_in, name='log_in'),
     path('user_login/', views.user_login, name='user_login'),
     path('user_logout/', views.user_logout, name='user_logout'),
]

user_authentication/user_authentication_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username + ' ' + self.user.email

user_authentication/user_authentication_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_authentication_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

user_authentication/user_authentication_app/views.py
from django.shortcuts import render
from user_authentication_app.forms import UserForm, UserInfoForm
from user_authentication_app.models import UserInfo
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.
def log_in(request):
    return render(request, 'user_authentication_app/login.html', context={})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('user_authentication_app:index'))
            else:
                return HttpResponse('Account is not active!!')
        else:
            HttpResponse('Login Details are Wrong!')
    else:
        return render(request, 'user_authentication_app/login.html', context={})
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_authentication_app:index'))

def index(request):
    diction = {'title':'home page'}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        diction = {'user_basic_info':user_basic_info,'user_more_info':user_more_info}
    return render(request, 'user_authentication_app/index.html', context=diction)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        userinfo_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and userinfo_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            userinfo = userinfo_form.save(commit=False)
            userinfo.user = user

            if 'profile_pics' in request.FILES:
                userinfo.profile_pic = request.FILES['profile_pics']

            userinfo.save()
            registered = True
    else:
        user_form = UserForm()
        userinfo_form = UserInfoForm()

    diction = {'user_form':user_form,'userinfo_form':userinfo_form, 'registered':registered}
    return render(request, 'user_authentication_app/register.html', context=diction)

user_authentication/templates/user_authentication_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{{ title }}</title>
  </head>
  <body>
      <nav class="navbar navbar-default">
       <div class="container-fluid">
         <div class="navbar-header">
           <a class="navbar-brand" href="{% url 'user_authentication_app:index' %}">User_Authentication</a>
         </div>
         <ul class="nav navbar-nav">
           <li class="active">
             <a href="{% url 'user_authentication_app:index' %}">Home</a>
           </li>
           {% if user.is_authenticated %}
           <li>
             <a href="{% url 'user_authentication_app:user_logout' %}">Logout</a>
           </li>
           {% else %}
           <li>
             <a href="{% url 'user_authentication_app:register' %}">Register</a>
           </li>
           <li>
             <a href="{% url 'user_authentication_app:log_in' %}">Login</a>
           </li>
           {% endif %}
         </ul>
       </div>
     </nav>

     <div class="container">
       {% block body_block %}

       {% endblock %}
     </div>
  </body>
</html>

user_authentication/templates/user_authentication_app/index.html
{% extends 'user_authentication_app/base.html' %}
{% block body_block %}
 {% if user.is_authenticated %}
 <p>{{user_basic_info.username}}</p>
 <p>{{user_basic_info.email}}</p>
 <a href="{{ user_more_info.facebook_id }}">Facebook Profile</a>
 <br>
 <img src="/media/{{ user_more_info.profile_pic }}" width="200px" height="200px">
 {% else %}
 <div class="alert alert-danger">
   <h3>You are not logged in!</h3>
 </div>
 {% endif %}
{% endblock %}

user_authentication/templates/user_authentication_app/login.html
{% extends 'user_authentication_app/base.html' %}
{% block body_block %}
<h3>Please Login</h3>
<form action="{% url 'user_authentication_app:user_login' %}" method="POST">
  <label for="username">Username</label>
  <input type="text" class="form-control" name="username" placeholder="Enter your username.." required>
  <br>
  <label for="password">Password</label>
  <input type="password" class="form-control" name="password" placeholder="Enter your password.." required>
  <br>
  {% csrf_token %}
  <input type="submit" name="submit" value="Login" class="btn btn-primary btn-sm">
</form>

{% endblock %}

user_authentication/templates/user_authentication_app/register.html
{% extends 'user_authentication_app/base.html' %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">
  <h3>Congratulations!! Registration Succesfull</h3>
</div>
{% else %}
<form class="" enctype="multipart/form-data" action="" method="POST">
  {{ user_form.as_p }}
  {{ userinfo_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register">
</form>
{% endif %}
{% endblock %}